apiVersion: nais.io/v1
kind: Naisjob
metadata:
  name: statuspoll
  namespace: navdig
  labels:
    team: navdig
spec:
  image: {{ image }}
  schedule: "*/3 * * * *"
  env:
    - name: TENANT
      value: nav.no
    - name: ENV
      value: prod
    - name: statusholder_url
      value: https://statusholder.prod-fss-pub.nais.io
    - name: portalserver_path
      value: http://portalserver
  azure:
    application:
      tenant: nav.no
      enabled: true
  accessPolicy:
    outbound:
      rules:
        - application: portalserver
          namespace: navdig
          cluster: prod-gcp
      external:
        - host: statusholder.prod-fss-pub.nais.io
        - host: aareg-status.intern.nav.no
        - host: nav.no
        - host: aa-registeret.nav.no
        - host: nav.no/person
