apiVersion: nais.io/v1
kind: Naisjob
metadata:
  name: statuspoll
  namespace: navdig
  labels:
    team: navdig
spec:
  image: {{ image }}
  schedule: "*/3 * * * *"
  env:
    - name: TENANT
      value: nav.no
    - name: ENV
      value: dev
    - name: statusholder_url
      value: https://statusholder.dev-fss-pub.nais.io
    - name: portalserver_path
      value: http://portalserver
  azure:
    application:
      tenant: nav.no
      enabled: true
  accessPolicy:
    outbound:
      rules:
        - application: portalserver
          namespace: navdig
          cluster: dev-gcp

