/*
 * Nav REST API
 * Documentation Nav portal REST API
 *
 * The version of the OpenAPI document: 0.1
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package no.nav.statusportalgcppoll;

import java.util.Arrays;
import java.util.List;

/**
* Gets or Sets Status
*/
public enum StatusDto {

    OK("OK"),
    ISSUE("ISSUE"),
    DOWN("DOWN");

    private String value;

    StatusDto(String value) {
        this.value = value;
    }

    public String getValue() {
        return value;
    }

    @Override
    public String toString() {
        return String.valueOf(value);
    }

    public static List<String> getValues() {
        return Arrays.asList(new String[] {
            "OK",
            "ISSUE",
            "DOWN",
        });
    }

    public static StatusDto fromValue(String text) {
        for (StatusDto b : StatusDto.values()) {
            if (String.valueOf(b.value).equals(text)) {
                return b;
            }
        }
        throw new IllegalArgumentException("Unexpected value '" + text + "' (should be one of " + getValues() + ")");
    }
}

